version: "3.9"

services:
  zed-ros2:
    build: .
    container_name: zed_ros2_container
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix    # GUI access for RViz2
      - /dev:/dev                        # Camera and USB access
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/zed:/usr/local/zed   # Mount host ZED SDK into container
    command: >
      bash -c "
      source /opt/ros/humble/setup.bash &&
      source /workspace/install/setup.bash &&
      ros2 launch zed_wrapper zed_camera.launch.py"
